"""Merge a committed, locally-generated network payload into the CI one.

The network payload is split along data-access lines: CI regenerates
``network.json`` daily from public snapshots (the archived bitnodes.io
crawls plus the bitnod.es CSV exports), while the KIT series can only be
built locally from the non-public dossiers and is committed as
``data/network-kit.json``. At deploy time the two are merged back into
the single ``network.json`` the frontend already consumes, so the split
is invisible to the web layer.

Merge rules, deliberately minimal:

- Sources from ``extra`` are grafted in only when ``base`` does not
  already carry a series of that name, so a source can migrate from
  committed to CI-generated by simply starting to produce it publicly.
- Every top-level key of ``base`` (diff banner, ``reference_timestamp``,
  ``schema_version``) wins: the banner should reflect the freshest,
  CI-built node set, and each grafted source still carries its own
  per-source ``latest_update``.
- A schema mismatch between the two files skips the graft with a
  warning instead of failing the deploy: a frozen committed file must
  never block shipping the fresh public payload after a schema bump.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

PathLike = str | Path


def merge_network_payloads(base_path: PathLike, extra_path: PathLike) -> dict | None:
    """Return the merged payload dict, or ``None`` when neither file exists.

    Either input may be missing: no ``base`` (CI produced no network
    section) falls back to ``extra`` as-is, and vice versa.
    """
    base = _load(base_path)
    extra = _load(extra_path)
    if base is None:
        return extra
    if extra is None:
        return base

    if base.get("schema_version") != extra.get("schema_version"):
        print(
            f"warning: {extra_path} carries schema "
            f"v{extra.get('schema_version')} but {base_path} is "
            f"v{base.get('schema_version')}; skipping the merge",
            file=sys.stderr,
        )
        return base

    base_sources = base.get("network", {}).get("sources", {})
    extra_sources = extra.get("network", {}).get("sources", {})
    for name, series in extra_sources.items():
        if name not in base_sources:
            base_sources[name] = series
    return base


def _load(path: PathLike) -> dict | None:
    path = Path(path)
    if not path.exists():
        return None
    return json.loads(path.read_text())
